[favorites.rust]
description = "New rust project with my preferred setups"
git = "https://github.com/aslowwriter/rust-template"
values = { handle = "aslowwriter", include_bin = true, include_bench = false }
