[ids]

# This is just for the numpad
145f:0239:c29ee854 
145f:0239:db085ee5
145f:0239:00b6695a

[main]

# don't want nmlock or space to give inputs if I'm just gonna use it as a cheap-o stream deck
# disable numlock so we can't randomly switch that off, I don't have a cd drive so this should be unused
numlock = ejectcd

# the numpad I have doesn't use KP_tab etc but normal tab and space keycodes which is bad
# because I still want to use those normally, so we fix that here, so that I can still bind 
# things to them in sway
space = kpequal
tab = kpplusminus
enter = kpenter


